[package]
name = "wcp"
version = "0.1.0"
authors = ["Remi Bernotavicius <remi@kunugiken.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http_io = { path = "../http_io" }
indicatif = "*"
structopt = "*"

[dev-dependencies]
tempfile = "*"
